languageCode = "en-us"
title = "Don't Panic"
baseURL = "https://commaok.xyz/"
theme = "hugo-cactus-theme"
publishDir = "docs"
rssLimit = 10

[params]
	name = "Josh Bleecher Snyder"
	description = "Words about Go"
	bio = "Gopher at large (currently burrowed)"
	twitter = "commaok"
	enableRSS = true

	# Navigation links
	home = ""
	#about = ""
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Go GDE"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"

[social]
    twitter  = "https://www.twitter.com/commaok"
    github   = "https://www.github.com/josharian"
